version: '2'

services:
  app:
    build: .
    command:
      - /app/run.sh
    
    expose:
      - "9000"
    ports:
      - "5004:5000"
    volumes:
      - .:/app
    links:
      - db
  db:
    image: mysql:5.6
    ports:
      - "3309:3306"
    expose:
      - "3309"
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    restart: always
volumes:
  dbdata:
