version: '2'

services:
  app:
    build: .
    command: php -S 0.0.0.0:5000 -t /app/web
    expose:
      - "9000"
    ports:
      - "5004:5000"
    volumes:
      - .:/app
    links:
      - db
    environment:
        XDEBUG_CONFIG: remote_host=172.17.0.1
        PHP_XDEBUG_ENABLED: 1

  db:
    image: mysql:5.6
    volumes:
      - xddb:/var/lib/mysql
    ports:
      - "3309:3306"
    expose:
      - "3309"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    restart: always

volumes:
  xddb:
